
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jresendiz' at '4/29/16 12:13 PM' with Gradle 2.12
 *
 * @author jresendiz, @date 4/29/16 12:13 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Assertions.assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
